config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'welcome#index' 

	resources :projects do
		resources :project_infos
	end
	
	resources :showcases
  resources "contacts", only: [:new, :create]

  match '/contacts', to: 'contacts#new',  via: 'get' 
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Haathi Contact Form",
      :to => "gloge@haathi-consulting.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ApplicationRecord
	mount_uploader :image, ImageUploader
	acts_as_taggable
	
	belongs_to :user
	has_many :project_infos
end

app/models/project_info.rb
class ProjectInfo < ApplicationRecord
	mount_uploader :image, ImageUploader
  belongs_to :project
end

app/models/showcase.rb
class Showcase < ApplicationRecord
	mount_uploader :image, ImageUploader
  belongs_to :user
  

  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 1500}
  
  validates_integrity_of  :image
  validates_processing_of :image
  
  validate :image_size_validation
  
  private
    def image_size_validation
      errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
    end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable 

  has_many :showcases
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout Proc.new { |controller| controller.devise_controller? ? 'form_layout' : 'application' }
  
  layout "form_layout", except: [:welcome]

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params| 
      user_params.permit(:password, :password_confirmation)
    end
    
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  layout "form_layout"

	def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if verify_recaptcha(model: @contact)
      @contact.deliver 
      redirect_to root_path, notice:  'Thank you. We will contact you soon!'
    else
      flash.now[:error] = 'Sorry, We can not seem to send this message.'
      render :new
    end
  end

  private
  def contact_params 
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/project_infos_controller.rb
class ProjectInfosController < ApplicationController
	before_action :authenticate_user!
	before_action :set_project_info, only: [:show, :destroy]
	before_action :set_project

	def index
		@project_infos = ProjectInfo.all
	end

	def new
	end

	def create
		@team_info = @project.project_infos.create(project_info_params)
		if @team_info.save
			redirect_to @project, notice: "success"
		else
			redirect_to @project, notice: "oops, not saved"
		end
	end

	def show
	end

	def destroy
		@project_info.destroy
		redirect_to @project, notice: "project_info successfully destroyed"
	end



	private
		def set_project_info
			@project_info = ProjectInfo.find(params[:id])
		end

		def set_project
			@project = Project.find(params[:project_id])
		end

		def project_info_params
			params.require(:project_info).permit(:image, :info)
		end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authenticate_user!,  except: [:show]
	before_action :set_project, only: [:show, :edit, :update, :destroy]

def new
	@project = current_user.projects.build

end

def create
	@project = Project.new(project_params)
	@project.user_id = current_user.id
	if @project.save
		redirect_to @project, notice: "project was successfully created"
	else
		render action: "new"
	end

end

def edit

end

def update
	if @project.update(project_params)
		redirect_to @project, notice: "project was updated"
	else
		render action: "edit"
	end
 
end

def destroy
	@project.destroy
	redirect_to root_path
end

def nl2br(s)
 	@s.gsub(/\n/, '<br>')
end

private
	def set_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:image, :image_cache, :title, :content, :link, :site_name , :tag_list)
	end
end

app/controllers/showcases_controller.rb
class ShowcasesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
  before_action :set_showcase, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def index
  end

  def new
    @showcase = current_user.showcases.build
  end
  
  def create
    @showcase = Showcase.new(showcase_params)
    @showcase.user_id = current_user.id
    if @showcase.save
      redirect_to @showcase, notice: 'showcase was successfully created'
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @showcase.update(showcase_params)
      redirect_to @showcase, notice: 'showcase was updated'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @showcase.destroy
    redirect_to root_path
  end
  
  
  private
  def set_showcase
   @showcase = Showcase.find(params[:id])   
  end
  def showcase_params
    params.require(:showcase).permit(:image, :image_cache, :title, :credit, :heading, :subheading, :content, :reference_info)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @user = User.find(params[:id])
      if user_params[:password].blank?
        user_params.delete(:password)
        user_params.delete(:password_confirmation)
      end
      if @user.update_attributes(secure_params)
      successfully_updated = if needs_password?(@user, user_params)
                               @user.update(user_params)
                             else
                               @user.update_without_password(user_params)
                             end
      end
      respond_to do |format|
        if successfully_updated
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def secure_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
    def needs_password?(user, params)
      params[:password].present?
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout "application"
	def index
		@showcases = Showcase.all
		@projects = Project.all
		@contact = Contact.new
		@project_infos = ProjectInfo.all
	end
	# def new
	# 	@contact = Contact.new
	# end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
  	base_title = "Haathi Consulting"
  	meta = "Websites that grow with you"
  	if page_title.empty?
    	base_title + ":" + meta
  	else
    	page_title + " | " + base_title
  	end
  end
  
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ""
  end

  def display_project_with_link(post)
      link_to image_tag(post.image.url(:project)), post
  end

    

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	include ActsAsTaggableOn::TagsHelper
  ActsAsTaggableOn.remove_unused_tags = true
  ActsAsTaggableOn.force_lowercase = true


end

app/helpers/showcases_helper.rb
module ShowcasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<div class="text-left container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div>
        <div>
          <h2>Hello</h2>
        </div>
        <div >
          <%= form_for(@contact) do |f| %>
            
           <div class="form-group">
             
              <%= f.text_field :name, required: true, class: "form-control" , placeholder: "Name"%>
            </div>
            <div class="form-group">
            
              <%= f.email_field :email, required:true, class: "form-control", placeholder: "Email" %>
            </div>
            <div class="form-group">
             
              <%= f.text_area :message, rows:3, required:true,  class: "form-control", placeholder: "Message" %>
            </div>

            <div class="form-group">
              <%= f.hidden_field :nickname, hint: "leave this part blank"%>
              <%= recaptcha_tags %>
            </div>
            
            

           <div class="btn-group">
                <%= f.submit "Send Message", class: "btn btn-primary" %>
            </div>
          <% end %>
          </div>
          <div class= "text-center">
            <h3> I promise to get back to you very soon </h3>
            <%= image_tag('laurie.jpg', class: "img-circle")  %> 
          </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact Us') %>
<section>
<div id="contact" class="text-left">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div>
        <div>
          <h2>Hello</h2>
        </div>
        <div >
          <%= form_for(@contact) do |f| %>
            
           <div class="form-group">
             
              <%= f.text_field :name, autofocus: true, required: true, class: "form-control" , placeholder: "Name"%>
            </div>
            <div class="form-group">
            
              <%= f.email_field :email, autofocus: true, required:true, class: "form-control", placeholder: "Email" %>
            </div>
            <div class="form-group">
             
              <%= f.text_area :message, autofocus: true, rows:3, required:true,  class: "form-control", placeholder: "Message" %>
            </div>

            <div class="form-group">
              
              <%= f.hidden_field :nickname, hint: "leave this part blank"%>
            </div>

           <div class="btn-group">
                <%= f.submit "Send Message", class: "btn btn-primary" %>
            </div>
          <% end %>
          </div>
          <div class= "text-center">
            <h3> I promise to get back to you very soon </h3>
            <%= image_tag('laurie.jpg', class: "img-circle")  %> 
          </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/layouts/_flash_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% if !flash.empty? %>

<div class = "container">
 <% flash.each do |key, value| %>
  <div class="row">
    <div class =  "col-lg-8 col-lg-offset-2 text-center">
      <div class="alert alert-<%= key %> fade_in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div> 

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="lower">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
         <span class="small">Copyright &copy; <span id="year"><%= Date.today.year %></span> - Haathi Consulting Inc. All Rights Reserved.</span>

        </div>
        
        <div class="col-md-3">
          <span class= "footer-link">
             <%= link_to 'https://github.com/TazzyG/tazzyg.github.io/blob/master/index.md', target: "_blank" do %>
             <i class = "fa fa-github fa-2x" %> </i> 
             <% end %>
          </span>
          <span class= "footer-link">
             <%= link_to 'https://www.linkedin.com/in/laurie-gloge-51193b3/', target: "_blank" do %>
             <i class = "fa fa-linkedin fa-2x" %> </i> 
             <% end %>
          </span>
          <span class= "footer-link">
             <%= link_to 'https://twitter.com/laurie_gloge', target: "_blank" do %>
             <i class = "fa fa-twitter fa-2x" %> </i> 
             <% end %>
          </span>
          


            
              
        </div>
        <div class="col-md-3 text-center">

        	<%= link_to new_contact_path do %> 
           
            <%= image_tag "haathi_log.png", class: "footer-image", alt: "creative calgary" %>
          <% end %>   
          
            
        </div>
      </div>
    </div>
  </div>
 
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Built with Ruby on Rails">
  <meta name="author" content="laurie gloge" >
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Rancho" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon'  %>
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>


  
  
  
  

app/views/layouts/_header.html.erb
<header id="my carousel" class="carousel slide carousel-fade intro-slider" data-ride="carousel" data-interval="10000">
  <!-- Indicators -->
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image: url(<%=asset_path 'redd-angelo-11908.jpg', {class: "img-responsive", alt: "haathi-consulting welcome"} %>);"></div>
      
    
      <div class="overlay"></div>

      <div class = "carousel-caption"> 
        <div class= "intro-body">
          <%= render 'layouts/flash_messages' %>
          <h1 class= "brand-heading">Websites Built With</h1>
          <h2 class= "brand-sub-heading">Ruby on Rails 
              <%= image_tag("ruby.png") %>
            </h2>
          
          
          <div>

            <a href="#about" class="btn btn-scroll-light sink">
              <i class= "fa fa-angle-down "></i>
            </a>
          </div>
        </div>
       
      </div>
    </div>
    <% @showcases.each do |showcase| %>
    <div class="item">

       <div class="fill" style="background-image: url(<%=asset_path showcase.image.url, {class: "img-responsive", alt: "haathi-consulting welcome"} %>);"></div>

      <div class="overlay"></div>
      <div class = "carousel-caption"> 
        <div class= "intro-body">
          <h1 class= "brand-heading">Websites Built With </h1>
          <h2 class= "brand-sub-heading"><%= showcase.title %></h2>
          
          <div>
            <a href="#about" class="btn btn-scroll-light sink">
              <i class= "fa fa-angle-down "></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </div>
  </div>  
</header>

app/views/layouts/_header_static.html.erb
<header 
  <div class="intro-img-half intro-dark-bg" style="background-image: 
  url(<%=asset_path "nikolas-behrendt-224067.jpg", {class: "img-responsive", alt: "haathi-consulting community websites"} %>);"></div>
  <div class="overlay"></div>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light navbar-fixed-top" role="navigation">
	<div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
          <i class="fa fa-bars"></i>
      </button>
      <span class="logo">
        <%= link_to root_path do %> 
        <h2>
        <%= image_tag("elephant.png") %>  
        HAATHI
        </h2>
        <% end %> 
      </span>
    </div>
		<div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
				<li class="hidden">
					<%= link_to root_path(:anchor => "hidden") %>
				</li>
				<li class= "page-scroll">
          <%= link_to "about", root_path(:anchor => "about") %>
				</li>
				<li class= "page-scroll">
          <%= link_to "projects",  root_path(:anchor =>"projects") %>
				</li>
        <li>
          <%= link_to "Contact", root_path(:anchor =>"contact")%>
        </li>
				
        <li>
          <% if user_signed_in? %>
            <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
          <% end %>
        </li>
			</ul>
		</div>		 
	</div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
 <%= render 'layouts/head'%>
  <body id="page-top"  data-target=".navbar-fixed-top"> 
		  <%= render 'layouts/nav' %>
		  <%= render 'layouts/header' %> 
   		<%= yield %>  
   		<%= render 'layouts/footer' %>  
 </body>
</html>

app/views/layouts/form_layout.html.erb
<!DOCTYPE html>
<html lang="en">
 <%= render 'layouts/head'%>
  <body id="page-top" data-target=".navbar-fixed-top", class= "intro-img fill text-light intro-dark-bg image_in_background" >
    <div id="wrapper">
      <%= render 'layouts/nav' %>
      <header></header>
      <section>
        <%= render 'layouts/flash_messages'%>
        <%= yield %>      
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/project_infos/_form.html.erb
<div>
<%= form_for([@project, @project.project_infos.build]) do |f| %>
    
    <div class="form-group">
      <%= f.hidden_field :project_id %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control", placeholder: "Select Image" %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group">
      <%= f.text_area :info, autofocus: true, class: "form-control", placeholder: "About this Screen Shot" %>
    </div>
    
    <div class="btn-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

<%= render "shared/image_script" %>

app/views/project_infos/_index.html.erb
<%= @project.project_infos.each do |project_info| %>     
  <div class="item">
    <%= image_tag project_info.image_url %>
  </div>
<% end %>
         

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved</h2>
      </ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        </div>
      <% end %>
  <% end %>
  <div class="form-group">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "title" %>
  </div>
  <div class="form-group">
    <%= f.text_field :link, autofocus: true, class: "form-control", placeholder: "link" %>
  </div>
  <div class="form-group">
    <%= f.text_field :site_name, autofocus: true, class: "form-control", placeholder: "site_name" %>
  </div>
  <div class="form-group">
    <%= f.label "features of this app"%><br />
    <%= f.text_area :content, autofocus: true, class: "form-control", wrap: "hard", placeholder:  "Tell us about the idea... \n example.. Grow some herbs and cook Italian meals... \n example .. Build a website", :text_area_html => {:maxlength => 260, :size => 300}  %>
    <%= f.label :tag_list, "Tags (separated by commas)" %><br>
    <%= f.text_field :tag_list, autofocus: true, class: "form-control", placeholder: "sample tags, map, search, calendar, payment functions" %>
  </div>
  
  <div class="form-group">
    <footnote>Upload your Banner Image - 1980 x 1320px</footnote>
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <%= f.hidden_field :image_cache %>
  </div>
  
  <div class="btn-group">
    <%= f.submit "Save project", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_modals.html.erb
<div id="modal1" class="portfolio-modal modal modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row first">
        <div class="col-lg-12">
          <h2 class= "page-header"> <%= @projects[0].title %> </h2>
          <h4> TEST </h4>
           <%= image_tag("benedicto-de-jesus-118405.jpg")%> 
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div id="project-details-carousel" class="owl-carousel owl-theme">
            <div class="item">
              <%= image_tag("benedicto-de-jesus-118405.jpg")%> 
            </div>
            <div class="item">
              <%= image_tag("dawid-zawila-221021.jpg")%> 
            </div>
            <div class="item">
              <%= image_tag("joe-mania-116449.jpg")%> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_tag_cloud.html.erb
<div id= "tag_cloud" class= "text-center container">
   <%= link_to "All ", root_path(:anchor => 'projects'), id: "all" %>
   <% tag_cloud @projects.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
   <% end %>
 </div>

app/views/projects/edit.html.erb
<div class="container text-left" id="edit_showcase">
  <div class = "row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class= "panel-heading">
          <h1>Edit Project</h1>
        </div>
        <div class = "panel-body">
          <%= render 'form', project: @project%>
        </div>
		    <div class= "panel-footer">
        <%= link_to 'Cancel - Show Project', @project %> 
        </div>
		  </div>  
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, "new project") %>
<div class= "container text-left" id="new_showcase">
  <div class= "row">
    <div class= "col-md-8 col-offset-2">
      <div class= "panel panel-default">
        <div class= "panel-heading">
          <h1> New Project Image</h1>
        </div>
        <div class= "panel-body">
          <%= render 'form', project: @project %>
        </div>
        <div class = "panel-footer">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, "Project" ) %>
<div class= "container text-left" id="new_showcase">
  <div class= "row">
    <div class= "col-md-8 col-offset-2">
      <div class= "panel panel-default">
        <div class= "panel-heading">
          <h1> <%= @project.title %></h1>
        </div>
        <div class= "panel-body">
         <p><%= image_tag @project.image_url %> </p>
         <p><%= @project.content %></p>
         <% if current_user %>
          <%= render "project_infos/form" %> 
         <% end %> 
        </div>
        <%= render "project_infos/index" %>
        <div class = "panel-footer">
          <% if current_user %> 
            <%= link_to 'Edit', edit_project_path(@project) %> | 
            <%= link_to 'Delete', @project, method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_image_script.html.erb
<script type="text/javascript">
  $('#showcase_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 15) {
      alert('Maximum file size is 15MB. Please choose a smaller file.');
    }
  });
</script>

app/views/showcases/_form.html.erb
<%= form_for @showcase, html: { multipart: true } do |f| %>
  <% if @showcase.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@showcase.errors.count, "error") %> prohibited this showcase from being saved</h2>
      </ul>
      <% @showcase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        </div>
      <% end %>
  <% end %>
  <div class="form-group">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "title" %>
  </div>

  <div class="form-group">
    <%= f.text_field :credit, autofocus: true, class: "form-control", placeholder: "image credit" %>
  </div>

  <div class="form-group">
    <%= f.text_field :heading, autofocus: true, class: "form-control", placeholder: "heading" %>
  </div>

  <div class="form-group">
    <%= f.text_field :sub_heading, autofocus: true, class: "form-control", placeholder: "subheading" %>
  </div>

  <div class="form-group">
    <%= f.text_field :reference_info, autofocus: true, class: "form-control", placeholder: "reference_info" %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, autofocus: true, class: "form-control", placeholder: "content" %>
  </div>
  
  <div class="form-group">
    <footnote>Upload your Banner Image - 1980 x 1320px</footnote>
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <%= f.hidden_field :image_cache %>
  </div>
  
  <div class="btn-group">
    <%= f.submit "Save showcase", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/showcases/_showcases.html.erb
<div>
  <%= @showcases.each do |showcase| %>
  	<% cache showcase do %>
      link_to image_tag(showcase.image.url(:slider)), showcase 
       <%= link_to 'Delete', showcase, method: :delete, data: { confirm: "Are you sure?" } %>  
    <% end %>  
  <% end %>
</div>

app/views/showcases/edit.html.erb
<div class="container text-left" id="edit_showcase">
  <div class = "row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class= "panel-heading">
          <h1>Edit showcase</h1>
        </div>
        <div class = "panel-body">
          <%= render 'form', showcase: @showcase%>
        </div>
		    <div class= "panel-footer">
        <%= link_to 'Cancel - Show showcase', @showcase %> 
        </div>
		  </div>  
    </div>
  </div>
</div>

app/views/showcases/new.html.erb
<% provide(:title, "new showcase") %>
<div class= "container text-left" id="new_showcase">
  <div class= "row">
    <div class= "col-md-8 col-offset-2">
      <div class= "panel panel-default">
        <div class= "panel-heading">
          <h1> New Showcase Image</h1>
        </div>
        <div class= "panel-body">
          <%= render 'form', showcase: @showcase %>
        </div>
        <div class = "panel-footer">
  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/showcases/show.html.erb
<% provide(:title, "Show Case" ) %>
<div class= "container text-left" id="new_showcase">
  <div class= "row">
    <div class= "col-md-8 col-offset-2">
      <div class= "panel panel-default">
        <div class= "panel-heading">
          <h1> <%= @showcase.title %></h1>
        </div>
        <div class= "panel-body">
         <p><%= image_tag @showcase.image_url %> </p>
         <p><%= @showcase.credit %>
        </div>
        <div class = "panel-footer">
          <%= link_to 'Edit', edit_showcase_path(@showcase) %> | 
          <%= link_to 'Delete', @showcase, method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_contact.html.erb
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-offset-2">
				
				<%= render 'contacts/form' %> 
			</div>
		</div>
	</div>